# Generated by Django 6.0.8 on 2026-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
